version: "3"
services:
  radarr:
    container_name: radarr
    restart: unless-stopped
    ports:
      - 7878:7878
    volumes:
      - /home/dockeras/radarr:/config
      - /mnt/nas/downloads:/downloads
      - /mnt/nas/tv_series:/movies
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Europe/Athens
    image: linuxserver/radarr

  sonarr:
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - /home/dockeras/sonarr:/config
      - /mnt/nas/downloads:/downloads
      - /mnt/nas/tv_series:/tv
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Europe/Athens
    image: linuxserver/sonarr
    networks:
      - nas-net

  jackett:
    container_name: jackett
    restart: unless-stopped
    ports:
      - 9117:9117
    volumes:
      - /home/dockeras/jackett:/config
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Europe/Athens
    image: linuxserver/jackett
    networks:
      - nas-net

  portainer:
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/dockeras/portainer:/data
    environment:
      - PUID=1000
      - PGID=150
      - TZ=Europe/Athens
    image: portainer/portainer
    networks:
      - nas-net

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022
      - WEBUI_PORT=8081
    volumes:
      - /home/dockeras/qbittorent/config:/config
      - /mnt/nas/downloads:/downloads
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8081:8081
    restart: unless-stopped
    networks:
      - nas-net

  lazylibrarian:
    image: ghcr.io/linuxserver/lazylibrarian
    container_name: lazylibrarian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/calibre-web:calibre|linuxserver/mods:lazylibrarian-ffmpeg #optional
    volumes:
      - /home/dockeras/lazylibrarian/:/config
      - /mnt/nas/ebook_download:/downloads
      - /mnt/nas/ebook:/books
    ports:
      - 5299:5299
    restart: unless-stopped
    networks:
      - nas-net
networks:
  nas-net:
    driver: bridge

